[tool.poetry]
name = "mws-malware-analysis"
version = "0.1.0"
description = ""
authors = ["sh-tak <shuhei.takekawa@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10, <3.11"
kaleido = "0.2.1"
optuna = "^3.4.0"
xgboost = "^2.0.0"
scikit-learn = "^1.0"
catboost = "^1.2.2"
torch = "^2.1.0"
seaborn = "^0.13.0"
autoviz = "^0.1.730"
ipykernel = "^6.25.2"
lightgbm = "^4.1.0"
pycaret = "^3.1.0"
imblearn = "^0.0"
umap-learn = "^0.5.4"
gensim = "^4.3.2"
mne = "^1.5.1"
python-levenshtein = "^0.23.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
